language: node_js
sudo: false
addons:
  code_climate:
    repo_token: "01f6b37045572411fc50c2f3ddf7a50f673f09a026dcaf40459b93ca1ea38d6a"
install:
  - "npm install"
script:
  - "npm run travis"
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
cache:
  directories:
    - 'node_modules'
